// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "RESTAPI": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=MYGO/studying/goa-design/design
// --out=$(GOPATH)/src/MYGO/studying/goa-design/infra
// --version=v1.3.1

package app
