// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "RESTAPI": Application Media Types
//
// Command:
// $ goagen
// --design=MYGO/studying/goa-design/design
// --out=$(GOPATH)/src/MYGO/studying/goa-design/infra
// --version=v1.3.1

package app

// Partner is address/customer/supplier/employee info (default view)
//
// Identifier: application/vnd.goa.partner+json; view=default
type GoaPartner struct {
	// Unique partner code
	Code *string `form:"Code,omitempty" json:"Code,omitempty" yaml:"Code,omitempty" xml:"Code,omitempty"`
	// Partner Identity
	ID *int `form:"ID,omitempty" json:"ID,omitempty" yaml:"ID,omitempty" xml:"ID,omitempty"`
	// Partner Name
	Name *string `form:"Name,omitempty" json:"Name,omitempty" yaml:"Name,omitempty" xml:"Name,omitempty"`
}
